### ISSUE TITLE
fill in readme

### ISSUE THREAD

**Issue by franzmoro** [tasminions/blog#21]

**Comment by sohilpandya** [comment]
Yes, fill it in. anything will do for now.

But seriously, spend the first couple of hours on the readme before even thinking about coding. And if you already did plan it out, can we see all the lovely photos of your drawing on the board.

**Comment by franzmoro** [comment]
very soon.. having some technical issues with android-mac interface. the whiteboard was our readme during the project.. we usually do write it in advance tho. i agree it's best to do so in future.
